spring.application.name=parabola-backend
spring.application.name=parabola-backend

spring.datasource.url=jdbc:mysql://localhost:3307/parabola_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=parabola_user
spring.datasource.password=parabola_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clerk JWK Set URI
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://grateful-boxer-13.clerk.accounts.dev/.well-known/jwks.json

