spring.application.name=parabola-backend

spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.krsoxhbcyrnrqpkrkzfl
spring.datasource.password=${SUPABASE_DB_PASSWORD:!parabola0826!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Clerk JWK Set URI
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://grateful-boxer-13.clerk.accounts.dev/.well-known/jwks.json

# Supabase Storage Configuration
supabase.url=${SUPABASE_URL:https://krsoxhbcyrnrqpkrkzfl.supabase.co}
supabase.anon-key=${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyc294aGJjeXJucnFwa3JremZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NjQ4ODEsImV4cCI6MjA5OTU0MDg4MX0.aNLgV1u0MLk94lUUvqnn47uuZ0AGmK5wp__aIJCqfpg}
supabase.bucket-name=${SUPABASE_BUCKET_NAME:product-images}
